# Where we'll write the TSV files from Google Sheets.
#
# You'll add these TSVs to the Git repository, and we'll generate pages from
# the TSV data. When journalists edit and publish the Google Sheet, that
# won't affect the repository until a developer refreshes it.
#
# If the code path is "app/sheets" and the slug is "index", the TSV data will
# go in "app/sheets/index.tsv".
basePath: data/google-sheets

sheets: []
